server:
  port: 8186

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yxw?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    # password: 123456
    password: Zhanghc2018
#    password: wjcbscb520
#    url: jdbc:mysql://47.96.147.242:3306/hlg_wf?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    username: hlgUser
#    password: hlg!1@2#3
mybatis-plus:
  check-config-location: true
  mapper-locations: classpath*:teamWeb/xml/*Mapper.xml
