server:
  session-timeout: 1800
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
file:
  doc-dir: static/doc/

spring:
  profiles:
    active: dev

